# Generated by Django 3.2.8 on 2021-10-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
