# Generated by Django 3.2.8 on 2021-10-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_alter_weatherdata_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
