# Generated by Django 3.2.8 on 2021-10-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_auto_20211005_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
